### ISSUE TITLE
Serve captured frame from capture_frame via Flask server

### ISSUE THREAD

**Issue by richiksc** [TheGreenMachine/GreenVision#11]
Using the Flask server integrated with `flask-opencv-streamer` we can serve anything we like - including the debug frame.

Tracking branch: [serve_captured_frame](../tree/serve_captured_frame)

- [x] Initial code
- [ ] Test
- [ ] Open PR
- [ ] Production

**Comment by ianmcvann** [comment]
I'm not sure this is needed in light of commit 6b30c61a487d2f3d77d4a9e0221844afddd443e7. What do you think @pdeutsch and @ddaymn?
